# Generated by Django 3.0.4 on 2020-03-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=100)),
                ('type', models.CharField(choices=[('S', 'Standard'), ('T', 'Thin'), ('P', 'Philadelphia'), ('H', 'Hot-Dog Crust')], default='S', max_length=100)),
                ('ingredients', models.ManyToManyField(blank=True, related_name='dishes_list', to='dishes.Ingredient')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
